# Generated by Django 3.2.6 on 2021-09-16 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=10)),
                ('priceAtBought', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purchasedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brokers.broker')),
            ],
        ),
    ]
