# Generated by Django 3.2.6 on 2021-09-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210925_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
