# Generated by Django 3.2.6 on 2021-09-25 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_broker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='broker',
            new_name='exchange',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='priceAtBought',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Bought Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Purchased Date'),
        ),
    ]
