# Generated by Django 3.2.6 on 2021-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20210925_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.IntegerField(default=1),
        ),
    ]
