# Generated by Django 3.2.6 on 2021-09-29 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='priceAtBought',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Purchased Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='Qty'),
        ),
    ]
