# Generated by Django 3.2.6 on 2021-09-30 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210929_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 30, 20, 52, 20, 135072, tzinfo=utc), verbose_name='Purchased Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transType',
            field=models.CharField(default='BUY', max_length=5, verbose_name='Type'),
        ),
    ]
