# Generated by Django 3.2.6 on 2021-10-01 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20210930_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 4, 11, 47, 272728, tzinfo=utc), verbose_name='Purchased Date'),
        ),
    ]
