# Generated by Django 3.2.6 on 2021-10-01 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_purchaseddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sold_qty',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 4, 40, 19, 848593, tzinfo=utc), verbose_name='Purchased Date'),
        ),
    ]
