# Generated by Django 3.2.6 on 2021-10-01 04:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20210930_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sold_qty',
            new_name='soldQty',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 4, 40, 41, 537593, tzinfo=utc), verbose_name='Purchased Date'),
        ),
    ]
