# Generated by Django 3.2.6 on 2021-10-04 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_auto_20210930_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='latestPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Latest Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchasedDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 15, 13, 54, 373163, tzinfo=utc), verbose_name='Purchased Date'),
        ),
    ]
